# Blog author setup
name: M-x Kelsin
desc: A Hacking Blog
author:
  name: Christopher Giroir
  email: kelsin@valefor.com

# Blog page setup
permalink: /:year/:month/:day/:title/
baseurl: /
url: http://mx.kelsin.net
paginate: 5
encoding: UTF-8

# Markdown settings
kramdown:
  input: GFM

# Syntax Highlighting
highlighter: rouge

# Approved github jekyll plugins
plugins:
  - jekyll-archives
  - jekyll-assets
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

# Include normally ignored files
include:
  - _redirects

# Ignore files meant for building
exclude:
  - .bowerrc
  - .bundle
  - .ruby-version
  - bower.json
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json

# Analytics
analytics:
  google: UA-24773156-4

sharing:
  twitter: kelsin5

# Social links
social:
  github: kelsin
  boardgamegeek: Kelsin
  bandcamp: kelsin
  facebook: kelsin
  twitter: kelsin5
  spotify: kelsin5

# Jekyll Archives
jekyll-archives:
  enabled:
    - tags
    - year
    - month
    - day
  layouts:
    tag: tag
    year: year
    month: month
    day: day
